name: Release Go JWT Tool

on:
  push:
    tags:
      - 'v*'   # e.g. v1.0.0

jobs:
  build:
    name: Build for Linux x86_64
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build binary
        run: |
          mkdir -p dist
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
            go build -o dist/jwt \
            -ldflags "-X main.version=$(git describe --tags --always) -X 'main.buildTime=$(TZ=America/Chicago date)'" \
            .

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: dist/jwt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
